version: '3'


volumes:  
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  postgres_data:
      driver: local
  
    
services:
  delivery:
    image: comd/delivery:latest 
    container_name: delivery
    network_mode: host
    ports:
      - "8090:8090"
    environment:
      - JCO_ASHOST=10.0.64.13
      - JCO_SYSNR=01
      - JCO_CLIENT=220
      - JCO_USER=amusa
      - JCO_PASSWD=jfoxuser     
     
  web:
    image: comd/creditnote-web:latest     
    container_name: web
    network_mode: host
    ports:
      - "8180:8180"
          
    depends_on:
      - delivery     
    environment:           
      - DELIVERY_SERVICE_URL=http://delivery:8090/comd-delivery-api/v1
      - CUSTOMER_SERVICE_URL=http://customer:9090/comd-customer-api/v1
      - CREDITNOTE_SERVICE_URL=http://creditnote:8085/comd-creditnote-api/v1
                   
  postgres:
      image: postgres
      container_name: postgres
      network_mode: host
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      
    
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    network_mode: host
    environment:      
      POSTGRES_DB: keycloak      
      DB_USER: keycloak      
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      #KEYCLOAK_CLIENT_REDIRECT_URIS: http://creditnote-web-host:8180/comd-creditnote-web
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    
    depends_on:
      - postgres
           

       

    

